### ISSUE TITLE
📧 Email collection

### ISSUE THREAD

**Issue by mountainash** [ginetta/ginetta-tonic-festival#6]
Please add to the homepage a way for people to register their interest in the event allowing us to send them a ticket purchase reminder when we are ready.

I believe Ginetta already has a Mailchimp account, please add a new MailingList to collect the signups.

- [x] add an `<input type="email" ` input form
- [x] add basic validation
- [x] send submission to mailing list on MailChimp
- [ ] Brand any email templates on Mailchimp with the Tonic branding
- [x] Tell the user "we won't sell your details - not even to event Sponsors - it's only for communications about upcoming Tonic Festivals. you can unsubscribe at any time. We use Mailchimp to handle our email services"
- [x] a  link to Mailchimps privacy policy

**Comment by mountainash** [comment]
@nlfonseca there's a new Audience on Mailchimp called "Tonic Festival - Website". Audience ID: `8a0e17de04`.

Below is the generated code needed to add a contact form to the Website. Please clean it up and style it to fit with this projects website.

```html
<div id="mc_embed_shell">
  
<div id="mc_embed_signup">
    <form action="https://ginetta.us2.list-manage.com/subscribe/post?u=f85cec9f0072f44befae4d9a1&amp;id=8a0e17de04&amp;f_id=00cf6ce0f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_self" novalidate="">
        <div id="mc_embed_signup_scroll">
            <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
            <div class="mc-field-group"><label for="mce-EMAIL">Email Address <span class="asterisk">*</span></label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""></div>
<div hidden=""><input type="hidden" name="tags" value="1537028,1537032,1537036,1537040"></div>
        <div id="mce-responses" class="clear">
            <div class="response" id="mce-error-response" style="display: none;"></div>
            <div class="response" id="mce-success-response" style="display: none;"></div>
        </div><div aria-hidden="true" style="position: absolute; left: -5000px;"><input type="text" name="b_f85cec9f0072f44befae4d9a1_8a0e17de04" tabindex="-1" value=""></div><div class="clear"><input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe"></div>
    </div>
</form>
</div>
</div>
```

**Comment by nlfonseca** [comment]
> @nlfonseca there's a new Audience on Mailchimp called "Tonic Festival - Website". Audience ID: `8a0e17de04`.
> 
> Below is the generated code needed to add a contact form to the Website. Please clean it up and style it to fit with this projects website.
> 
> ```
> <div id="mc_embed_shell">
>   
> <div id="mc_embed_signup">
>     <form action="https://ginetta.us2.list-manage.com/subscribe/post?u=f85cec9f0072f44befae4d9a1&amp;id=8a0e17de04&amp;f_id=00cf6ce0f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_self" novalidate="">
>         <div id="mc_embed_signup_scroll">
>             <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
>             <div class="mc-field-group"><label for="mce-EMAIL">Email Address <span class="asterisk">*</span></label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""></div>
> <div hidden=""><input type="hidden" name="tags" value="1537028,1537032,1537036,1537040"></div>
>         <div id="mce-responses" class="clear">
>             <div class="response" id="mce-error-response" style="display: none;"></div>
>             <div class="response" id="mce-success-response" style="display: none;"></div>
>         </div><div aria-hidden="true" style="position: absolute; left: -5000px;"><input type="text" name="b_f85cec9f0072f44befae4d9a1_8a0e17de04" tabindex="-1" value=""></div><div class="clear"><input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe"></div>
>     </div>
> </form>
> </div>
> </div>
> ```

okay 👌
